project_name: training-cli

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/ondrejsika/training-cli/version/version.Version=v{{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"
      - goos: linux
        goarch: arm
        goarm: 6
    binary: training-cli

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: training-cli
    conflicts:
      - training-cli-edge
    tap:
      owner: ondrejsika
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/ondrejsika/training-cli
    url_template: "https://github.com/ondrejsika/training-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/ondrejsika/training-cli"
    description: "training-cli"
    install: |
      bin.install "training-cli"
    test: |
      system "#{bin}/training-cli version"
  -
    name: training-cli-edge
    conflicts:
      - training-cli
    tap:
      owner: ondrejsika
      name: homebrew-tap
    skip_upload: false
    homepage: https://github.com/ondrejsika/training-cli
    url_template: "https://github.com/ondrejsika/training-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/ondrejsika/training-cli"
    description: "training-cli"
    install: |
      bin.install "training-cli"
    test: |
      system "#{bin}/training-cli version"

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "ondrejsika/training-cli:{{ .Tag }}"
      dockerfile: Dockerfile
      ids:
        - training-cli
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/ondrejsika/training-cli"
        - "--label=maintainer=Ondrej Sika &lt;ondrej@sika.io&gt;"
    - goos: linux
      goarch: arm64
      image_templates:
        - "ondrejsika/training-cli:{{ .Tag }}-arm64v8"
      dockerfile: Dockerfile.arm64v8
      ids:
        - training-cli
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/ondrejsika/training-cli"
        - "--label=maintainer=Ondrej Sika &lt;ondrej@sika.io&gt;"

scoop:
  bucket:
    owner: ondrejsika
    name: scoop-bucket
  homepage:  https://github.com/ondrejsika/training-cli
  description: CLI Help for Ondrej Sika's Training
  license: MIT
